import moment from 'moment'
import Head from 'next/head'
import ChannelDetails from '../../components/ChannelDetails'
import Header from '../../components/Header'
import Secondheader from '../../components/Secondheader'

function Channel(props) {
    const allData = props.allData.response
    // console.log(allData.schedule["2021-09-17"])
    return (
        <div>
            <Head>
                <title>Channel | Astro Content Guide</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <Header />
            <Secondheader />

            <main className='max-w-7xl mx-auto px-8 md:px-36'>
              <ChannelDetails
                key={allData.id}
                channelId={allData.id}
                title={allData.title}
                img={allData.imageUrl}
                stbNo={allData.stbNumber}
                desc={allData.description}
                time={allData.schedule["2021-09-23"].map((item) => moment(item.datetimeInUtc).format("LT"))}
                progTitle={allData.schedule["2021-09-23"].map((item) => (item.title))}
              />
            </main>

        </div>
    )
}

export default Channel

export async function getStaticPaths() {
  const channelId = await fetch('https://contenthub-api.eco.astro.com.my/channel/all.json').then(
      (res) => res.json()
    );

  const paths = channelId.response.map(item => {
      return {
        params: { cid: item.id.toString() }
      }
    })
  // console.log('wdfbwrbhw')

  return {
      paths,
      fallback: false
  }
}

export async function getStaticProps(paths) {
  const id = paths.params.cid
  const allData = await fetch(`https://contenthub-api.eco.astro.com.my/channel/`+ id +`.json`).then(
    (res) => res.json()
  );

  // console.log(allData)

  return {
    props: {
      allData,
    }
  }
}