import Head from 'next/head'
import Image from 'next/image'
import Banner from '../components/Banner'
import Categorycard from '../components/Categorycard'
import ChannelList from '../components/ChannelList'
import Header from '../components/Header'
import Secondheader from '../components/Secondheader'

export default function Home(props) {
  const allData = props.allData
  // console.log(props.allData.response[0].currentSchedule[0].datetime)
  return (
    <div>
      <Head>
        <title>Channels | Astro Content Guide</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <Secondheader />
      <Banner />

      <main className='max-w-7xl mx-auto px-8 md:px-36'>
        <section className='pt-6'>
          <h2 className='text-2xl lg:text-3xl font-bold pt-3'>Category</h2>

          <div className='flex space-x-3 overflow-x-auto scrollbar-hide p-3 pt-0 -ml-3'>
            <Categorycard />
          </div>
        </section>

        <div className='grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-3'>
          {allData.response.map((item) => (
            <ChannelList
              key={item.id}
              channelId={item.id}
              title={item.title}
              img={item.imageUrl}
              stbNo={item.stbNumber}
              nowTime={item.currentSchedule.map((item) => (item.datetimeInUtc))}
              nowProgramTitle={item.currentSchedule.map((item) => (item.title))}
              nextTime={item.currentSchedule.map((item) => (item.datetimeInUtc))}
              nextProgramTitle={item.currentSchedule.map((item) => (item.title))}
              nextTime2={item.currentSchedule.map((item) => (item.datetimeInUtc))}
              nextProgramTitle2={item.currentSchedule.map((item) => (item.title))}
            />
          ))}
        </div>
      </main>
    </div>
  )
};

export async function getStaticProps() {
  const allData = await fetch('https://contenthub-api.eco.astro.com.my/channel/all.json').then(
    (res) => res.json()
  );

  return {
    props: {
      allData,
    }
  }
}
